### ISSUE TITLE
How to specify additional dependencies?

### ISSUE THREAD

**Issue by ustun** [pre-commit/mirrors-eslint#4]
I added 

```
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: aaa8651ac4833f38c66a6b1b475856f4b1e01c57
    hooks:
    -   id: eslint
    -   additional_dependencies: ['babel-eslint', 'eslint-plugin-babel', 'eslint-plugin-react']
```

But it doesn't automatically install the packages. Should I go to the folder in ~/.pre-commit/ and install them manually?

**Comment by ustun** [comment]
Seems like there is no way to add additional_deps once the repo is pulled. Should I create another repo where I specify the additional deps?

**Comment by asottile** [comment]
You'll need to also include eslint in your `additional_dependencies` (at least for node mirrored packages) since that's how it gets installed as a workaround for https://github.com/pre-commit/pre-commit/issues/282

See: https://github.com/pre-commit/mirrors-eslint/blob/aaa8651ac4833f38c66a6b1b475856f4b1e01c57/hooks.yaml#L9

So your config would look like:

```
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: aaa8651ac4833f38c66a6b1b475856f4b1e01c57
    hooks:
    -   id: eslint
        additional_dependencies: ['eslint', 'babel-eslint', 'eslint-plugin-babel', 'eslint-plugin-react']
```

**Comment by asottile** [comment]
pre-commit should automatically handle and recreate repositories if it notices changes in additional_dependencies since version 0.7.0 (added here: https://github.com/pre-commit/pre-commit/pull/319)

**Comment by ustun** [comment]
Thanks, should have searched the issues first.

**Comment by asottile** [comment]
No problem! Thanks for the report :D
